'use client';

import { useState, useRef, useEffect, use } from 'react';
import { useRouter } from 'next/navigation';
import UserLayout from '@/components/user/UserLayout';
import type { UserInfo } from '@/components/user';

// User info
const userInfo: UserInfo = {
  name: 'Alex Morgan',
  role: 'Product Manager',
  avatarUrl:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDAmMk59qSMKpRVgwH2-1ZDpW6tKM38LzF_D2PkTMlKp1MRLUYyvBJv6pzs5hmEj_Ms49FXBhTRWNuYd8XcQigCjuI_cRobr6p1uXnLaCpn5XLRHdlVLFwFbQsrrhDTsPlq14duIlIxFoh6jfXb2KKRc4GXTeiQRyEHuVNKRGQK5B_Ns_XRB9ISjjUiK0AGBXqsXLv5H1w1AJUCfJN2RBS12NROZqQGRjEuUBDZS-WbM3q6VY4et6I_O3dEUiu1ePU2ouvHipUnR7g',
};

// Chatbot information based on ID
const chatbotInfo: Record<string, any> = {
  '1': {
    name: 'IT Support Bot',
    icon: 'dns',
    iconColor: 'text-blue-500',
    iconBg: 'bg-blue-500/10',
    category: 'IT Support',
  },
  '2': {
    name: 'HR Policy Bot',
    icon: 'diversity_3',
    iconColor: 'text-pink-500',
    iconBg: 'bg-pink-500/10',
    category: 'Human Resources',
  },
  '3': {
    name: 'SOP Master',
    icon: 'menu_book',
    iconColor: 'text-emerald-500',
    iconBg: 'bg-emerald-500/10',
    category: 'Operations',
  },
  default: {
    name: 'AI Assistant',
    icon: 'smart_toy',
    iconColor: 'text-primary',
    iconBg: 'bg-primary/10',
    category: 'General',
  },
};

interface Message {
  id: string;
  type: 'bot' | 'user';
  content: string;
  timestamp: string;
  sources?: Array<{ title: string; page?: number }>;
}

export default function UserChatPage({ params }: { params: Promise<{ id: string }> }) {
  const router = useRouter();
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const { id } = use(params);
  const bot = chatbotInfo[id] || chatbotInfo.default;

  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      type: 'bot',
      content: `Hello! I'm the ${bot.name}. How can I assist you today?`,
      timestamp: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
    },
  ]);
  const [inputMessage, setInputMessage] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isSaved, setIsSaved] = useState(false);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isTyping]);

  const handleSendMessage = () => {
    if (!inputMessage.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      type: 'user',
      content: inputMessage,
      timestamp: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInputMessage('');
    setIsTyping(true);

    // Simulate bot response
    setTimeout(() => {
      const botMessage: Message = {
        id: (Date.now() + 1).toString(),
        type: 'bot',
        content:
          "I understand your question. Based on our documentation, here's what I found: This is a sample response from the AI assistant. In a real implementation, this would be generated by your AI model based on the user's query and the knowledge base.",
        timestamp: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        sources: [
          { title: 'Employee_Handbook_2024.pdf', page: 12 },
          { title: 'IT_Support_Guide.docx', page: 5 },
        ],
      };
      setMessages((prev) => [...prev, botMessage]);
      setIsTyping(false);
    }, 1500);
  };

  const handleKeyPress = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setInputMessage(e.target.value);
    // Auto-resize textarea
    e.target.style.height = 'auto';
    e.target.style.height = `${Math.min(e.target.scrollHeight, 200)}px`;
  };

  const handleNewRequest = () => {
    router.push('/user/dashboard');
  };

  const handleSaveThread = () => {
    setIsSaved(!isSaved);
  };

  const handleBackToHistory = () => {
    router.push('/user/history');
  };

  return (
    <UserLayout
      userInfo={userInfo}
      onNewRequest={handleNewRequest}
      showNewRequestButton={false}
    >
      <div className="max-w-5xl mx-auto h-full flex flex-col">
        {/* Chat Header */}
        <div className="flex items-center justify-between pb-6 border-b border-[#2d3544]">
          <div className="flex items-center gap-4">
            <button
              onClick={handleBackToHistory}
              className="text-slate-400 hover:text-white transition-colors"
            >
              <span className="material-symbols-outlined">arrow_back</span>
            </button>
            <div className={`size-12 rounded-lg ${bot.iconBg} ${bot.iconColor} flex items-center justify-center`}>
              <span className="material-symbols-filled text-2xl">{bot.icon}</span>
            </div>
            <div>
              <h2 className="text-white text-xl font-bold">{bot.name}</h2>
              <p className="text-slate-400 text-sm">{bot.category}</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={handleSaveThread}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                isSaved
                  ? 'bg-primary/20 text-primary border border-primary/30'
                  : 'bg-[#1e2430] text-slate-300 border border-[#2d3544] hover:border-slate-500'
              }`}
            >
              <span className={isSaved ? 'material-symbols-filled' : 'material-symbols-outlined'}>
                bookmark
              </span>
              <span className="hidden sm:inline">{isSaved ? 'Saved' : 'Save Thread'}</span>
            </button>
            <button className="bg-[#1e2430] text-slate-300 border border-[#2d3544] hover:border-slate-500 px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2">
              <span className="material-symbols-outlined text-lg">download</span>
              <span className="hidden sm:inline">Export</span>
            </button>
          </div>
        </div>

        {/* Messages Area */}
        <div className="flex-1 overflow-y-auto py-6 space-y-6 min-h-0">
          {messages.map((message) => (
            <div key={message.id} className={`flex gap-4 ${message.type === 'user' ? 'justify-end' : ''}`}>
              {message.type === 'bot' && (
                <div className={`size-10 rounded-lg ${bot.iconBg} ${bot.iconColor} flex items-center justify-center flex-shrink-0`}>
                  <span className="material-symbols-filled text-xl">{bot.icon}</span>
                </div>
              )}
              <div className={`flex flex-col gap-2 max-w-[80%] ${message.type === 'user' ? 'items-end' : ''}`}>
                <div
                  className={`rounded-2xl px-5 py-3 ${
                    message.type === 'user'
                      ? 'bg-primary text-white'
                      : 'bg-[#1e2430] text-white border border-[#2d3544]'
                  }`}
                >
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">{message.content}</p>
                </div>
                {message.sources && message.sources.length > 0 && (
                  <div className="flex flex-col gap-2 mt-1">
                    <p className="text-xs text-slate-500 font-medium">Sources:</p>
                    <div className="flex flex-wrap gap-2">
                      {message.sources.map((source, idx) => (
                        <div
                          key={idx}
                          className="flex items-center gap-2 bg-[#1e2430] border border-[#2d3544] rounded-lg px-3 py-1.5 text-xs text-slate-300 hover:border-primary/50 transition-colors cursor-pointer"
                        >
                          <span className="material-symbols-outlined text-sm text-slate-500">description</span>
                          <span className="font-medium">{source.title}</span>
                          {source.page && <span className="text-slate-500">• p.{source.page}</span>}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
                <span className="text-xs text-slate-500">{message.timestamp}</span>
              </div>
              {message.type === 'user' && (
                <div className="size-10 rounded-lg bg-primary/20 text-primary flex items-center justify-center flex-shrink-0 font-semibold text-sm">
                  {userInfo.name
                    .split(' ')
                    .map((n) => n[0])
                    .join('')
                    .toUpperCase()}
                </div>
              )}
            </div>
          ))}

          {/* Typing Indicator */}
          {isTyping && (
            <div className="flex gap-4">
              <div className={`size-10 rounded-lg ${bot.iconBg} ${bot.iconColor} flex items-center justify-center flex-shrink-0`}>
                <span className="material-symbols-filled text-xl">{bot.icon}</span>
              </div>
              <div className="bg-[#1e2430] border border-[#2d3544] rounded-2xl px-5 py-3">
                <div className="flex gap-1.5">
                  <div className="size-2 bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                  <div className="size-2 bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                  <div className="size-2 bg-slate-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                </div>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="pt-6 border-t border-[#2d3544]">
          <div className="relative">
            <textarea
              ref={textareaRef}
              value={inputMessage}
              onChange={handleInputChange}
              onKeyPress={handleKeyPress}
              placeholder="Type your question here... (Shift+Enter for new line)"
              className="w-full bg-[#1e2430] border border-[#2d3544] text-white rounded-xl px-5 py-4 pr-14 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent placeholder-slate-500 resize-none transition-all min-h-[56px] max-h-[200px]"
              rows={1}
            />
            <button
              onClick={handleSendMessage}
              disabled={!inputMessage.trim()}
              className="absolute right-3 bottom-3 size-10 bg-primary hover:bg-blue-600 disabled:bg-slate-700 disabled:cursor-not-allowed text-white rounded-lg flex items-center justify-center transition-colors"
            >
              <span className="material-symbols-outlined">send</span>
            </button>
          </div>
          <p className="text-xs text-slate-500 mt-3 text-center">
            AI responses are generated based on internal documentation. Always verify critical information.
          </p>
        </div>
      </div>
    </UserLayout>
  );
}
